// <auto-generated />
using System;
using EmployeeManagementSystem.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementSystem.Migrations
{
    [DbContext(typeof(EMScontext))]
    [Migration("20221222084409_attempt7")]
    partial class attempt7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagementSystem.Model.Designation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("employeeDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("employeeDetailsId");

                    b.ToTable("designations");
                });

            modelBuilder.Entity("EmployeeManagementSystem.Model.EmployeeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genderid")
                        .HasColumnType("int");

                    b.Property<string>("Mailid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("designationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("EmployeeManagementSystem.Model.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("EmployeeDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("EmployeeDetailsId");

                    b.ToTable("genders");
                });

            modelBuilder.Entity("EmployeeManagementSystem.Model.Designation", b =>
                {
                    b.HasOne("EmployeeManagementSystem.Model.EmployeeDetails", "employeeDetails")
                        .WithMany("Designation")
                        .HasForeignKey("employeeDetailsId");

                    b.Navigation("employeeDetails");
                });

            modelBuilder.Entity("EmployeeManagementSystem.Model.Gender", b =>
                {
                    b.HasOne("EmployeeManagementSystem.Model.EmployeeDetails", "EmployeeDetails")
                        .WithMany("gender")
                        .HasForeignKey("EmployeeDetailsId");

                    b.Navigation("EmployeeDetails");
                });

            modelBuilder.Entity("EmployeeManagementSystem.Model.EmployeeDetails", b =>
                {
                    b.Navigation("Designation");

                    b.Navigation("gender");
                });
#pragma warning restore 612, 618
        }
    }
}
